{"uuid": "5ef884c8-277f-4d60-b134-651295fb041e", "children": ["bd670bb7-2c37-4810-b0bd-da67187a27eb"], "befores": [{"name": "db_connection", "status": "broken", "statusDetails": {"message": "psycopg2.OperationalError: could not translate host name \"db\" to address: Name or service not known\n\n", "trace": "  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 891, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\tests\\api\\conftest.py\", line 25, in db_connection\n    conn = psycopg2.connect(**DB_PARAMS)  # Устанавливаем соединение с БД\n  File \"C:\\Users\\volch\\Desktop\\Diplom\\.venv\\Lib\\site-packages\\psycopg2\\__init__.py\", line 135, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\n"}, "start": 1742463118529, "stop": 1742463121221}], "start": 1742463118529, "stop": 1742463121342}